### ISSUE TITLE
Error when converting simple equation - Language not supported by T1 fontenc encoding.

### ISSUE THREAD

**Issue by r-menezes** [humenda/GladTeX#13]
I am attempting to use `gladtex` in some simple html code, but found this error.
Is this something simple to solve?

**test.htex**
```{html}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <title>Test</title>
</head>
<body>
<p>Inline: <eq env="math">\sigma  \nu \! \sigma  \tau  \eta  \mu  \alpha</eq> </p>
</body>
</html>
```

**to reproduce**
```
$ gladtex test.htex

> Error while converting formula 0 at line 0, 0:
>    \sigma  \nu \! \sigma  \tau  \eta  \mu  \alpha
>Formula without unicode symbols:
>
>Language not supported by T1 fontenc encoding; please report this to the GladTeX project.
```

I am using GladTeX 2.3.1

**Comment by humenda** [comment]
Thanks for the report. What is your system locale on your system? You did not
specify a character setting in the HTML head, nor on the command-line (using
-E), so what I get is:

```
Error while parsing /tmp/q.htex: Could not determine encoding of document, no charset information in the HTML header found.
```

Using the -E option, it works fine for me, so I suspect a bug in the locale
guessing of the code.

**Comment by r-menezes** [comment]
Thank you for the very fast response!

my locale:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
```

I attempted setting LANGUAGE to `en_US.UTF-8` and the results were the same.

I then added the line `<meta charset="UTF-8" />` to the head of the htex file and now running `gladtex -E UTF-8 test.htex` gives the same result but running `gladtex test.htex` prints:
```
Traceback (most recent call last):
  File "/usr/bin/gladtex", line 310, in <module>
    m.run(sys.argv)
  File "/usr/bin/gladtex", line 167, in run
    docparser.feed(doc)
  File "/usr/lib/python3/dist-packages/gleetex/htmlhandling.py", line 73, in feed
    document = document.decode(encoding)
LookupError: unknown encoding: 
```

Later I can attempt to install GladTeX from source to see if there was something wrong with the `apt` installation, if it helps

**Comment by humenda** [comment]
Ah, so you're running GladTeX as packaged in Debian (or Ubuntu and all of it
descendants)?
In this case, please try to run from source and test:

1.  Without any encoding (neither on the command-line nor in the HTML).
2.  With `-E UTF-8`.
3.  With charset from the HTML file.

The lookup error is strange, but I won't be able to reproduce this before
Sunday.

**Comment by r-menezes** [comment]
> Ah, so you're running GladTeX as packaged in Debian (or Ubuntu and all of it
descendants)?

yes

I ran the tests:
1. `Error while parsing test.htex: Could not determine encoding of document, no charset information in the HTML header found.`
2. Works !
3. Works !

I think it is safe to say that this is bug is not present on the current version, but only on the Debian/descendents distros' package.
Now I've installed from source everything runs smoothly. Perhaps you could recommend installation through source on the README.md ?

Another suggestion:
when looking on `gladtex --help` I had the impression that by using `-p preamble.tex` the file content would be added to the preamble of the .tex file gladtex creates. Maybe you could add something like:
"In order to add the contents of a file on the preamble, use -p \\input{file}" ?

**Comment by humenda** [comment]
Thanks for running the tests.

>> Ah, so you're running GladTeX as packaged in Debian (or Ubuntu and all of it
>descendants)?
>
>yes

What version is this? On my Debian Buster machine, that's 3.1 and that's also
the quasi-current source. Are you running some Ubuntu* LTS version with an
older GladTeX?

Since it runs fine on Debian stable and I happen to be the maintainer of the
Debian package as well, I am a bit reluctant to add anything to the README,
unless this applies to some older Ubuntu* LTS version.

>Another suggestion:
>when looking on `gladtex --help` I had the impression that by using `-p preamble.tex` the file content would be added to the preamble of the .tex file gladtex creates. Maybe you could add something like:

It says:

```
  -p LATEX_STATEMENT    Add given LaTeX code to preamble of document; that'll
                          affect the conversion of every image
```

I would say that this explains that a statement (or correctly speaking a
macro) needs to be given. But I will add your stanza.

**Comment by humenda** [comment]
Please check the latest formulation in the man page (manpage.md) or in the source code. Is this now more descriptive?

**Comment by r-menezes** [comment]
I am running Ubuntu 18.04.5 LTS.
The output of `apt show gladtex` is:

```
Package: gladtex
Version: 2.3.1-1
Priority: optional
Section: universe/text
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Sebastian Humenda <shumenda@gmx.de>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 29.7 kB
Depends: python3:any, python3-gleetex
Suggests: pandoc
Homepage: http://gladtex.sourceforge.net
Download-Size: 9420 B
APT-Sources: http://br.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
Description: Embed LaTeX equations in HTML files
 GladTeX is a preprocessor that enables the use of LaTeX equations within HTML
 files. The equations, embedded in <EQ>...</EQ> tags, as if within $$..$$ in
 LaTeX, is fed through LaTeX and replaced by images.
 .
 Additionally all images get an alt-tag for alternative texts that contains the
 LaTeX-equivalent of the image. This is handy for text-mode browsers or blind
 people using a screen reader.
```

I was able to install version 3.1.0 with `pip install gladtex` and `python setup.py install` when inside gladtex folder downloaded with `git clone ...`

Puzzling, I could not reproduce the error after removing the version installed with `pip` / `setup.py` and  installing gladtex again with `sudo apt install gladtex` with version 2.3.1-1. When running the test 1. above, it simple worked.

I might have inadvertently created some strange setup  the first time I installed.
I guess this is well solved. Also, on the new description in the man page is clearer. Indeed it was correct the first time, but the new writing might avoid people jumping into conclusions and making the same mistake I have.

Thank you for all the support again !

**Comment by humenda** [comment]
Thanks for looking it up. I remember vaguely that there has been an issue with
encodings and it is possible that 2.3.x still has it. Since This is already
Ubuntu "old stable", current LTS is 20.04, I would like to keep the README as
it is. Thanks for reporting and also for suggesting an improvement.
