### ISSUE TITLE
Use SVG instead of PNG for formulas

### ISSUE THREAD

**Issue by SushiTee** [humenda/GladTeX#9]
I played around with dvisvgm a bit.

It also returns _width_, _height_ and _depth_. Just like dvipng does. It is just printed in a different way:

```
dvisvgm -n -e --comments .\eqn012.dvi
pre-processing DVI file (format version 2)
processing page 1
  computing extents based on data set by preview package (version 11.91)
  width=51.925522pt, height=15.012513pt, depth=10.28363pt
  graphic size: 51.925522pt x 25.296143pt (18.249734mm x 8.890578mm)
  output written to eqn012.svg
1 of 1 page converted in 0.19 seconds
```

It returns the values as _pt_. Those values need to be converted to _bp_ which is more or less the Tex equivalent to _px_ in html. To do so you can just do: [bp = pt * (72.27/72)](https://github.com/mgieseki/dvisvgm/blob/master/src/DVIToSVG.cpp#L234)

dvisvgm uses the constant 72.27/72 to convert from bp to pt.

Also the values dvisvgm returns seem to be correct while the values from dvipng seem to be wrong.

dvipng returns this for the same test image:

```
dvipng --width* --depth* --height* .\eqn012.dvi
This is C:\Program Files\MiKTeX 2.9\miktex\bin\x64\dvipng.exe (dvipng) 1.15 Copyright 2002-2015 Jan-Ake Larsson
[1 (preview-latex version 11.91) (preview-latex tightpage option detected, will
use its bounding box) depth=14 height=21 width=72]
```

Embedding the created converted image into the html document where it should be the formula converted using dvisvgm fits perfectly into the line while the image created with dvipng is too far at the botom of the line and the aspect ratio seems to be a bit off, too.

Suggested command to convert formulas using divsvgm:
__dvisvgm -n -e -o <output file name> <dvi file>__

-n: don't use fonts but pathes. In case some characters are missing in the fonts which would be used otherwise (e.g. the sum character did not work in my tests otherwise)
-e: calculates the exact bounding rect.

**Comment by humenda** [comment]
This is already implemented.
See latest master.
Thanks
-- 
Web: https://www.crustulus.de (English|Deutsch)  | Blog: https://www.crustulus.de/blog
FreeDict: Free multilingual dictionaries - http://www.freedict.org
Freies Latein-Deutsch-Wörterbuch: https://www.crustulus.de/freedict.de.html

**Comment by SushiTee** [comment]
Well it's not in master. I didn't see the other branch. Sorry.

are you sure that is correct?

```
# convert from pt to px
(float(v) * 1.3333333 for v in found.groups())))
```

You should add -n and -e option.

**Comment by humenda** [comment]
>are you sure that is correct?
Yes, it is. E. g. 7.5pt 10 pt → ~1.333

>You should add -n and -e option.
Sorry, what should I add?

**Comment by SushiTee** [comment]
https://github.com/humenda/GladTeX/blob/3ab86127b9c820927df4389ed5f323e33254fc21/gleetex/image.py#L286

on that line add "-n" and "-e"

-n, --no-fonts[=variant]      draw glyphs by using path elements [0]
-e, --exact                   compute exact glyph boxes

It prevents the usage of fonts. I had the problem that not everything was drawn correctly using fonts (e.g. the sum charcter).

**Comment by humenda** [comment]
>on that line add "-n" and "-e"
Commit 5f573f64 already introduced `--no-fonts`.

**Comment by SushiTee** [comment]
> Yes, it is. E. g. 7.5pt 10 pt → ~1.333

I think it's not that simple. the pt to px conversion depends on dpi. It is probably a good idea to just use _pt_ in the final HTML document. Well modern browsers asume 96dpi. There 1.33333 is correct.

The stuff I wrote with 72.27 / 72 was wrong as it is just the ratio of TeX points to HTML points. dvisvgm already takes care of it.

Still the formula is placed wrong into the html document. You should use the graphics size for _width_ and _height_. 

As you can see there is a difference in the height:

```
  width=51.925522pt, height=15.012513pt, depth=10.28363pt
  graphic size: 51.925522pt x 25.296143pt
```

When using the _height_ from the first line there will be white spaces left and right fomr the formula and the formula is scaled according to that hight which will make the characters a lot smaller than the surrounding text.


> Commit 5f573f64 already introduced `--no-fonts`.

There is no such commit. Also I searched the whole code in master and add_dvisvg_support. I didn't find it anywhere.

**Comment by humenda** [comment]
Please make a PR for your changes.
Do you use the latest dvisgm? 2.4.1 has a bug with the formula placement.

**Comment by SushiTee** [comment]
was using the one which was installed by miktex 2.3.3. I updated to 2.5 and tried everything again.

The bug that part of the image are cut off is gone when using --scale=1.2 but the characters in the formula are a bit bigger than the surrounding text like this. If this is wanted it is ok though.
The problem with the white spaces left and right is the same. So it is needed to use the values from "graphic size" and everything is perfect.

**Comment by humenda** [comment]
As I said, `--scale' is what the author recommended to me. Have you tried
looking at the results in different browsers? This unfortunately also influences
the font size to image size ratio :).
In any case, I'd be happy to merge a PR with your changes.
Thanks

**Comment by SushiTee** [comment]
> In any case, I'd be happy to merge a PR with your changes.

Will do.
